### ISSUE TITLE
Write to Maria DB

### ISSUE THREAD

**Issue by SpeedevilReal** [marvin-mangold/-S7-PLC_MySql_MariaDB#8]
Hello,

Reading from my SQL Databse works fine, but i want to Write into the Maria DB, that works also good. But the Query i write, need to be variable.

For Example

'Write into Protocoll Where Name is Temperature #actuallytemperature'

(So the string, needs a Tag inside which gets his Data from a AnalogInput Value.

Can you help me with this?

**Comment by marvin-mangold** [comment]
Hello,
yes this is possible.

The query command you typed in in the datablock for your test is a string.

So you can write your Command in the first String and execute the query. 
For example:

Call IntToString
- IN= #actuallytemperature
- OUT= #tempString

Call Concat
- IN1= 'Write into Protocoll Where Name is Temperature '
- IN2= #tempString
- OUT= "SQL".querydata [0]

Set execute input.

-------------------------

Because the query command is an array of strings you can also type the first part of your command in the first string and the second part in the second string and execute it. it will be concatenated automatically.

For example:

Call Move
- IN1= 'Write into Protocoll Where Name is Temperature '
- OUT= "SQL".querydata[0]

Call IntToString
- IN= #actuallytemperature
- OUT= "SQL".querydata[1]

Set execute input.

**Comment by SpeedevilReal** [comment]
thank you very much, that sounds good.

But now my Problem is i have  120 Values :-) so i would need 240 Strings. 120 Commands for the table and 120 values. 

I try to extend the Function block from 5 to 240. whta do you think?

**Comment by marvin-mangold** [comment]
The InOut "querydata Array[*]" is dynamic, so for exapmle you could connect a Array[0..119] to the InOut.

This should write the strings into the sendbuffer automatically. 

You need to change the constant "#Buffersize" of the FB to the new size + x. 
As Standard it is 4096 Bytes.

Give it a try, if you need more help or there is a problem i will help as soon as i can. 

Never tried to send this amount of data, but it should work.

**Comment by SpeedevilReal** [comment]
Hello @marvin-mangold  its me again, 

i tried to Write into the maria db and it works well, but now i have a question again,

between every column in my database in the query i need a ",". so for example my query would look likes this:

INSERT INTO DATABASE.TEST ( Temperature,WINDSPEED,TIMEOFTODAY) Values (Tag1,Tag2,Tag3)';


But you know i have 120 Tag, so do i need between every tag an extra Tag with "," that at the End my Complete String has a "," between every tag. Or do you have an beeter Idea? I dont want to Boost my Query up to 240 Strings from 120 only for a simple "," between every Tag.

Do you know what i mean? Everything Else looks great, but this is for now my last thing to need to complete my project.

Thanks in advance for your great work!

**Comment by marvin-mangold** [comment]
I would say it really depends on how you structure your data.

Let's say you want to enter 120 values ​​in the database.

Then I would create an array [0..119] with the column name and the corresponding value. 
And would say for start every column Name is maximal 50 letters and every Value is max 50 letter (String[50]).

![3](https://github.com/user-attachments/assets/4df7fe01-7768-4452-b1e2-98fea3e07093)

You then fill this, i.e. the column name would remain unchanged and you would convert the value into a string and write it into the array. As soon as all the data has been entered, I would write a function that always packs 4 names/values ​​together into a string.

![23](https://github.com/user-attachments/assets/b09773a4-b218-4619-86e1-f07b75a8109a)

So now the SQL command is 16 Strings long and not 240 String long anymore.
![1](https://github.com/user-attachments/assets/ecf5e730-b65b-44aa-961b-95cccf32cde7)
![2](https://github.com/user-attachments/assets/369e5a5e-931f-4dc2-9608-bbbd4a7cad09)

**Comment by SpeedevilReal** [comment]
Good Evening @marvin-mangold  Thanks a lot for your great answer. I rebuild it, and it looks nearly good. But now of course i have my next problem. 

The LEN Command cuts the The String after 200 letters. But Of course if i try it with empty values for example 0.0 i have another size of the string then in real conditions, where i have maybe 2.5 oder 12.0 Degrees. 

Ok now you see the Names works fine 118 "Names" but in Value i have only 117 Values. The last 1 Value is lost.

If i change the LEN Command to for example 105 or something it goes better or worse. So it thins something is not correct with my Len command. Do you have an Idea?

These are my Convert Commands
![Konvert](https://github.com/user-attachments/assets/bb4e74d6-e1ee-4407-8c9e-c4e2e7a16221)


Here at the End should be an +35.0 but its lost. So normally i would expect one more String only with the value 35.0 Of Course i have typed in at the Value Field in my Array.
(The rows below doesnt matter, they are form playing with the Len Command.
![DB 34 0](https://github.com/user-attachments/assets/67f48880-b628-49d6-92f6-7f60fae01475)

Thank YOU!

**Comment by marvin-mangold** [comment]
Because for this example I first specified that the data in the array was a maximum of 50 bytes long (String[50]), I thought it would be best to combine 4 values ​​into one string. That's why I made the cut at LEN(200). Since a string can have a maximum of 254 bytes. I can't tell you where exactly your error comes from. 

If you can't find the error you can always use Call Concat to combine 4 values ​​and write them into a string instead of using For loops etc.

something like this:

![Unbenannt](https://github.com/user-attachments/assets/0c51ce35-227c-4936-bc4e-c9766c86e920)

**Comment by SpeedevilReal** [comment]
I reduce the size of Name an Value to [35] so would "cut it at 70 or 140.
But it still doesnt work, i thin i know the Problem.
![grafik](https://github.com/user-attachments/assets/5c360a81-0302-4641-80e9-5efd0ff8b40d)


The TempStrings are for example 75 long ok, but the last one is ony  29 long and then the command :

IF LEN(#TempString1) > 70
        
    THEN
        #DatenbankInstanz.SollQueryFürSchreiben.Strings[#DatenbankInstanz.SollQueryFürSchreibenPointer] := #TempString1;
        #DatenbankInstanz.SollQueryFürSchreibenPointer := #DatenbankInstanz.SollQueryFürSchreibenPointer + 1;
        #TempString1 := '';
    END_IF;

Isn´t True and the loop will close the Array. So the String with 29 is lost...

I will try a solution and write an comment
