### ISSUE TITLE
Tested with MariaDB 11.5, several Problems 

### ISSUE THREAD

**Issue by AlpixTM** [marvin-mangold/-S7-PLC_MySql_MariaDB#9]
Hey Marvin,

we tested your software with a MariaDB 11.5, although it's only listed compatible to 11.2.

At the beginning, we could read from the db without a problem.

But then we failed to write a dataset.
Out of 30–50 times, it only worked for one or two times.
Also, at the end,  we weren't able to read the db anymore.
Connected stayed on true, but we reconnected for several times to debug.
Of course we had set server to 2.

The mariaDB Log logged aborted connections:

> 2024-10-23 13:31:54 43 [Warning] Aborted connection 43 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)
> 2024-10-23 13:46:18 56 [Warning] Aborted connection 56 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)
> 2024-10-23 13:50:35 57 [Warning] Aborted connection 57 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)
> 2024-10-23 13:55:51 58 [Warning] Aborted connection 58 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)
> 2024-10-23 14:01:21 59 [Warning] Aborted connection 59 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)
> 2024-10-23 14:05:40 60 [Warning] Aborted connection 60 to db: 'test' user: 'your_new_username' host: '172.17.200.168' (Got an error reading communication packets)

Do you think our issue is connected to the mariaDB Version?
Will it be compatible in the future?

**Comment by marvin-mangold** [comment]
Hi,
I dont think it is related to the MariaDB Version.

Are you using the Functionblock as is or have you changed some Parameters?

What is the Value of the "Status" Output while this error occurs?

Maybe there Are Hardware issues? Bad Connection/Cables?

----------------------------

You can also get these errors if you send a query to the server that is incorrect or too large. If mysqld receives a packet that is too large or out of order, it assumes that something has gone wrong with the client and closes the connection. If you need big queries (for example, if you are working with big BLOB columns), you can increase the query limit by setting the server's max_allowed_packet variable, which has a default value of 1MB. You may also need to increase the maximum packet size on the client end. More information on setting the packet size is given in Section C.5.2.10, “Packet too large”.


An INSERT or REPLACE statement that inserts a great many rows can also cause these sorts of errors. Either one of these statements sends a single request to the server irrespective of the number of rows to be inserted; thus, you can often avoid the error by reducing the number of rows sent per INSERT or REPLACE.

Try raising the max_allowed_packet to a much larger number, since the default is 1M. 

To set the max_allowed_packet to 256M, you can add it to /etc/my.cnf or my.ini

[mysqld]
max_allowed_packet=256M
to cover future restarts of mysqld. To install the value now on the server, please run this:

SET GLOBAL max_allowed_packet = 1024 * 1024 * 256;

**Comment by AlpixTM** [comment]
Hey,

thy for your reply.


We just changed the params like the password and query and so on.
Status for writing was always #0000.
At first we had login and syntax errors (for select) and status code #0012, but after that we always had 0000, even when reading did not work anymore.
I changed the data type of the ID and Value col from INT(11) to INT(24), can this be the reason why reading stopped working?

Connection is very stable, we never had network issues in our network.
I cant rule out hardware issues, but theres no signs for that.

We dont send or read big packages, we have the same test data like in your video, and we try to set one record (the 5 record like in your video).
Should we still increase it?

What can we do next?

Test if it works with 11.2?

Lukas

**Comment by marvin-mangold** [comment]
If you have time to test it with 11.2 then i would prefer this.

I'm curious if it works with 11.2 then. But I think it must be something else.

**Comment by AlpixTM** [comment]
Hey Marvin,

We retested it today with MariaDB 11.5.

0) The connection closed error comes if you set connect to false

1) I can read again, I had to change datatype of ID and Value from INT(24) back to INT(11).

2) We were able to write one dataset again.

3) This did not show up when we do select right aftert (change query stmt and then set query to true). I thinke we needed to reconnect.

4) We werent able to write another dataset (8, "eight", 888)

5) If we did a select after the (failed) insert, it did not change the (empty) result, after we did a ping this worked...

Whats the usage of the ping param?

**Comment by AlpixTM** [comment]
Ive tried with MariaDB 11.2

1. I selected a existing db, but the table was not existing. When I select, there was no error (no msg and status #0000), so I think there may be other situations where there is an error that still leeds to #0000 
2. The result was not blank if there was a valid result before, so you still see the old result. If old was blan, it stayed blank.

**Comment by marvin-mangold** [comment]
Ok I understand, then the sql server seems to complain because the connection is simply terminated without sending a quit package first.

This could be implemented, but it is thought that you stay connected for a long time, so i didnt think about it. 

-----

The ping Command is for checking of the Server is still alive and Connection.

The Idea was to keep connected to the Server as long as the machine/PLC is running, and at some Point of the machine cycle you can check via ping if Server ist alive to Not start the production or measuring without connected sql Server.

-----

Do you connect and then query and then disconnect or do you keep the connect turned on?

Maybe the sql Server disconnects After some time by itself?

**Comment by marvin-mangold** [comment]
In the instance datablock there  is a section called error packet. There you can find a human readable Error Message from the SQL Server is it sends an error. Maybe this sohws hey Int(24) is a Problem

**Comment by AlpixTM** [comment]
> Ok I understand, then the sql server seems to complain because the connection is simply terminated without sending a quit package first.

> This could be implemented, but it is thought that you stay connected for a long time, so i didnt think about it.

Yes. I dont care about that, but the error msg in the log doent seem to be connected with our issues.


> The ping Command is for checking of the Server is still alive and Connection.

Okay, so that ping helped to get the live data was just coincidence, not a wanted feature


>Do you connect and then query and then disconnect or do you keep the connect turned on?

>Maybe the sql Server disconnects After some time by itself?

No, but I thought that disconnect might help if we see old data (from the result before, but not error). I thought this might be a cache, but its more like the old result because of the error that does not report it self.

> In the instance datablock there is a section called error packet. There you can find a human readable Error Message from the SQL Server is it sends an error

Yes, there were typical sql messages if erorr status was not #0000 but in our cases there was no error and no msg



Will look into the encoding next

**Comment by AlpixTM** [comment]
Collocation of db and table is utf8/utf8_gerneral_ci => utf8mb3_gerneral_ci

We get connected = true, Errror = #0000 but no en empty result...

Query Select * from data; works in MSQLWorkbench...

**Comment by marvin-mangold** [comment]
You can change the plc COLLATION in the FB Code:

CLIENTINFO![image](https://github.com/user-attachments/assets/b1fc4787-eeab-4e1c-afb0-db399285aea6)

These Are the values:

![image](https://github.com/user-attachments/assets/f8c71a23-e820-4826-b9ca-6d707dabae8e)

**Comment by AlpixTM** [comment]
with 33/ utf8 / utf8_gerneral_ci you mean utf8mb3_gerneral_ci and not the new standard utf8mb4_gerneral_ci, right?

It was already set to 33

**Comment by marvin-mangold** [comment]
33 is utf8mb3_general_ci 


https://mariadb.com/kb/en/supported-character-sets-and-collations/#collations

**Comment by AlpixTM** [comment]
Right we are using this the whole time.
We got to read once again, but since that the result data stays the same, but no error whatsoever is showing up...

**Comment by marvin-mangold** [comment]
Is it possible to send me a wireshark capture of the communication between plc and Server?

**Comment by AlpixTM** [comment]
Will look for that on monday, wrote you on linkedin.

can this be a result of connecting and disconnecting?
Can this cause chaos?
Because once i read the database of an old connection (changed 10 minutes before to another databasename) but suddenly read data from the old db...

**Comment by marvin-mangold** [comment]
Sounds like there is something weird happening. You could stop the plc and/or change then Connection ID Parameter of the FB. Maybe the PLCs tcp stuff is messed up somehow.

**Comment by AlpixTM** [comment]
Yes,

this fixed the proplem on the sport, the next query will work as expected.

But the next after it wont work anymore, even if the stmt stays the same, if i update the data on the sql server, it wont update in result if I set query to true

**Comment by AlpixTM** [comment]
Changing the connection did not change anything, will try to reboot the PLC to check if the fix is reproducible

**Comment by marvin-mangold** [comment]
I will have a look at this issue if I have some minutes this weekend. If there are some changes in the Version that lead to this Problems then I will find it.

**Comment by AlpixTM** [comment]
I found a fix:

We only had your DB on the SPS, we had a cycle time of 1ms.

I've set the minimum cycle time to 10ms, then it worked like a charm.
I reproduced it several times, the low cycle time is the problem.

**Comment by marvin-mangold** [comment]
Sounds Great! 
I will add this to the Projects Readme. Did it run with MariaDB 11.5? So i can add this too.

If you have any further question feeling free to ask!

**Comment by AlpixTM** [comment]
Will test it with 11.5

But I think the underlying issue may be a wrong - or not existant - wait for a handshake or something like this, else beeing fast (= done all work) would be no problem? 
I think this should be looked into, because maybe this can also occur with 10ms cycles if the package needs longer than normal.

**Comment by marvin-mangold** [comment]
Absolutely! I will have a look and close this issue when i am done. 
Thank you for your patience and for findig the bug! 👍🏻

**Comment by AlpixTM** [comment]
@marvin-mangold 
Thx for the fix.

The mechanism to wait for a fully received package looks like the right step, but it still does not work with fast cycles :(

**Comment by AlpixTM** [comment]
TIA was not able to set query to 1 securely with this low cycletimes...

Now everything is working, this can be closed
